### ISSUE TITLE
The New Yorker incomplete extraction

### ISSUE THREAD

**Issue by rozbb** [adbar/trafilatura#234] opened 2022-08-09 18:20 UTC
Extracting [this article](https://www.newyorker.com/magazine/2022/08/15/the-reluctant-prophet-of-effective-altruism) yields only the text up to the words "Ord reallocated", about 1/5 of the way through the article.

It appears that the full article does appear in the HTML though. It's copied 4 times, actually. It's a little hard to see but just search short strings of the article in the source and you'll see it.

**Comment by adbar** [comment] 2022-08-16 14:40
Hi @rozbb, thanks for reporting the issue. I believe it is a duplicate of #85 (and also #159) so I am going to close this thread.

**Comment by adbar** [comment] 2022-08-16 14:40
Hi @rozbb, thanks for reporting the issue. I believe it is a duplicate of #85 (and also #159) so I am going to close this thread.

**Closed by adbar** 2022-08-16 14:40 UTC
