### ISSUE TITLE
LXML 5.2.0 breaks import

### ISSUE THREAD

**Issue by marban** [adbar/trafilatura#532] opened 2024-03-31 09:49 UTC
`ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
`

**Comment by rithvikshetty** [comment] 2024-04-01 07:21
I tried installing it separately, and the error doesn't come up. But, `bare_extraction()` stops working.

**Comment by cyber-emreclskn** [comment] 2024-04-01 09:37
same problem anyone solve this????
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.

**Comment by romanthegentle** [comment] 2024-04-01 13:33
I downgraded to lxml == 5.1.0
And that solved it for me

**Comment by cyber-emreclskn** [comment] 2024-04-01 13:53
but i use trafilatura package inside lxml. And i try this solution. Not worked me!!!

**Comment by UmairAhmadBaltoro** [comment] 2024-04-01 15:03
using lxml==5.1.0 will fix your problem..

**Comment by adbar** [comment] 2024-04-02 11:50
Alternatively you can update Trafilatura to its latest version (1.8.0), `lxml.html.clean` has been removed.

**Comment by adbar** [comment] 2024-04-02 13:58
This is now fixed in #535, I'll issue a new Trafilatura release shortly.

**Comment by adbar** [comment] 2024-04-03 11:48
The issue is now fixed in release 1.8.1.

**Closed by adbar** 2024-04-03 11:48 UTC
Labels: bug

**Comment by adbar** [comment] 2024-04-04 09:51
It's already done, or can you be more specific?

**Comment by adbar** [comment] 2024-04-08 11:29
It's normal, that's the bug fix for now.

**Comment by adbar** [comment] 2024-05-13 11:30
LXML will be up-to-date in the next version, see #593.
