### ISSUE TITLE
Fallback for parsing sitemap data

### ISSUE THREAD

**Issue by trisongz** [adbar/trafilatura#64] opened 2021-03-31 00:40 UTC
Hi, I just discovered this lib and it's quickly becoming one of my favorites due to how quick and clean it works!

I wanted to bring up an issue/potential fix for sitemap parsing, with the end goal of extracting all the urls from the sitemap.

Using the url `https://hubspot.com` as the example

Using the native method
```python3
from trafilatura import sitemaps, feeds

feed_url = "https://hubspot.com"

rss_list = feeds.find_feed_urls(feed_url, target_lang='en')
print(rss_list)

"""
returns

WARNING:root:not a valid XML sitemap: https://hubspot.com/sitemap.xml
WARNING:root:not a sitemap: https://hubspot.com/sitemap.xml
[] # returns empty list
"""

# then if searching by sitemap_search function
sitemap_list = sitemaps.sitemap_search(feed_url, target_lang='en')
print(sitemap_list)

"""
returns

ERROR:trafilatura.utils:not a 200 response: 404 for URL https://hubspot.com/sitemap_news.xml
WARNING:root:not a sitemap: https://hubspot.com/sitemap_news.xml
ERROR:trafilatura.utils:not a 200 response: 404 for URL https://hubspot.com/sitemap_index.xml
WARNING:root:not a sitemap: https://hubspot.com/sitemap_index.xml
WARNING:trafilatura.sitemaps:Diverging domain names: hubspot.com sitemaps.org
WARNING:trafilatura.sitemaps:Diverging domain names: hubspot.com google.com
WARNING:trafilatura.sitemaps:Diverging domain names: hubspot.com google.com
WARNING:trafilatura.sitemaps:Diverging domain names: hubspot.com hubspotusercontent00.net
WARNING:trafilatura.sitemaps:Diverging domain names: hubspot.com hubspotusercontent00.net
WARNING:trafilatura.sitemaps:Diverging domain names: hubspot.com hubspotusercontent00.net
WARNING:trafilatura.sitemaps:Diverging domain names: hubspot.com hubspotusercontent00.net
WARNING:trafilatura.sitemaps:Diverging domain names: hubspot.com hubspotusercontent00.net
WARNING:root:not a valid XML sitemap: https://hubspot.com/sitemap.xml.gz
WARNING:root:not a sitemap: https://hubspot.com/sitemap.xml.gz
['https://www.hubspot.com/careers/error</loc><lastmod>2019-11-06</lastmod></url><url><loc>', 
'https://www.hubspot.com/case-studies/incenteev</loc><lastmod>2021-03-05</lastmod></url><url><loc>', ...]
# returns unclean list of results
"""
```
However, the first sitemap found in find_feed_urls is valid, it's just missing the <xml> encoding that the function looks for.

So what I had done instead was

```python3
from trafilatura import bare_extraction

feed_url = 'https://hubspot.com/sitemap.xml'

downloaded = fetch_url(feed_url)
result = bare_extraction(downloaded, output_format='python', include_links=True)

# probably better with regex
links_list = result['text'].split('https://')
links_list = [('https://' + l).strip() for l in links_list if l]
```

This returns a list of > 1k urls. If it would be possible to return valid 200 found sitemaps from find_feed_urls function, regardless of whether the function is able to successfully parse it, it would be very useful (perhaps as an arg). 

Thanks for this awesome lib!

**Comment by adbar** [comment] 2021-03-31 16:59
Hi @trisongz, thanks for your feedback!

The link extractor was giving up too easily on particular types of XML sitemaps, treating them as TXT files. It is fixed now.

I cannot reproduce the first part of your script: `feeds.find_feed_urls(feed_url, target_lang='en')` returns nothing without even looking for sitemaps. This is logical since there are no feeds to be found.

**Comment by trisongz** [comment] 2021-03-31 23:12
Hi @adbar, thanks for looking into it!

In reference to the first post, the  `feeds.find_feed_urls(feed_url, target_lang='en')` function does indeed return nothing `[]` - however, the logs from running showed a valid xml URL, (which the logger said was `valid XML sitemap`) which is what I had used to validate and test with the remaining functions with.

**Comment by adbar** [comment] 2021-04-01 14:45
Alright, I cannot reproduce it so I guess it's also been fixed in the repository version.

**Closed** 2021-04-06 03:09 UTC
Labels: bug
