### ISSUE TITLE
Unhandled TypeError — possible regression?

### ISSUE THREAD

**Issue by tadeoos** [adbar/trafilatura#60] opened 2021-03-16 18:32 UTC
Hey,
I noticed that a fair amount of extractions are failing with a seemingly unnecessary TypeError.

steps to reproduce:

```python
downloaded = trafilatura.fetch_url('https://fortelabs.co/blog/para/')
trafilatura.extract(downloaded, include_links=True)
```

gives:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-28-33fce83a7b3f> in <module>
----> 1 trafilatura.extract(downloaded, include_formatting=False, include_links=True)

/usr/local/lib/python3.8/site-packages/trafilatura/core.py in extract(filecontent, url, record_id, no_fallback, include_comments, output_format, tei_validation, target_language, include_tables, include_images, include_formatting, include_links, deduplicate, date_extraction_params, with_metadata, max_tree_size, url_blacklist, settingsfile, config)
    776         url_blacklist = set()
    777     # extraction
--> 778     docmeta = bare_extraction(
    779         filecontent, url=url, no_fallback=no_fallback,
    780         include_comments=include_comments, output_format=output_format,

/usr/local/lib/python3.8/site-packages/trafilatura/core.py in bare_extraction(filecontent, url, no_fallback, include_comments, output_format, target_language, include_tables, include_images, include_formatting, include_links, deduplicate, date_extraction_params, with_metadata, max_tree_size, url_blacklist, config)
    682
    683         # extract content
--> 684         postbody, temp_text, len_text, sure_thing = extract_content(cleaned_tree, include_tables, include_images, include_links, deduplicate, config)
    685
    686         # compare if necessary

/usr/local/lib/python3.8/site-packages/trafilatura/core.py in extract_content(tree, include_tables, include_images, include_links, deduplicate, config)
    382         # list(filter(None.__ne__, processed_elems))
    383         result_body.extend([e for e in
--> 384                             [handle_textelem(e, potential_tags, deduplicate, config) for e in subtree.xpath('.//*')]
    385                             if e is not None])
    386         # remove trailing titles

/usr/local/lib/python3.8/site-packages/trafilatura/core.py in <listcomp>(.0)
    382         # list(filter(None.__ne__, processed_elems))
    383         result_body.extend([e for e in
--> 384                             [handle_textelem(e, potential_tags, deduplicate, config) for e in subtree.xpath('.//*')]
    385                             if e is not None])
    386         # remove trailing titles

/usr/local/lib/python3.8/site-packages/trafilatura/core.py in handle_textelem(element, potential_tags, dedupbool, config)
    287         new_element = handle_titles(element)
    288     elif element.tag == 'p':
--> 289         new_element = handle_paragraphs(element, potential_tags, dedupbool, config)
    290     elif element.tag == 'lb':
    291         if text_chars_test(element.tail) is True:

/usr/local/lib/python3.8/site-packages/trafilatura/core.py in handle_paragraphs(element, potential_tags, dedupbool, config)
    171                     newsub.set('rend', child.get('rend'))
    172                 elif child.tag == 'ref':
--> 173                     newsub.set('target', child.get('target'))
    174             # handle line breaks
    175             elif child.tag == 'lb':

src/lxml/etree.pyx in lxml.etree._Element.set()

src/lxml/apihelpers.pxi in lxml.etree._setAttributeValue()

src/lxml/apihelpers.pxi in lxml.etree._utf8()

TypeError: Argument must be bytes or unicode, got 'NoneType'
```

I believe this error could be handled in a meaningful way (perhaps excepted and passed?), but maybe I'm missing something?

**Comment by adbar** [comment] 2021-03-16 19:44
Hi, thanks for the bug report, it goes farther than this `TypeError`, it's now fixed in the repository but I'll have to look deeper into it.

**Comment by tadeoos** [comment] 2021-03-17 16:56
Indeed, I'm getting a different error now:

```
In [9]: trafilatura.extract(downloaded, include_links=True)
INFO:trafilatura.core:using custom extraction: None
INFO:trafilatura.core:not enough comments None
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/app/main/choices.py in <module>
----> 1 trafilatura.extract(downloaded, include_links=True)

/usr/local/lib/python3.8/site-packages/trafilatura/core.py in extract(filecontent, url, record_id, no_fallback, include_comments, output_format, tei_validation, target_language, include_tables, include_images, include_formatting, include_links, deduplicate, date_extraction_params, with_metadata, max_tree_size, url_blacklist, settingsfile, config)
    811         docmeta['fingerprint'] = content_fingerprint(docmeta['raw-text'])
    812     # return
--> 813     return determine_returnstring(docmeta, output_format, include_formatting, include_links, tei_validation)
    814
    815

/usr/local/lib/python3.8/site-packages/trafilatura/core.py in determine_returnstring(docmeta, output_format, include_formatting, include_links, tei_validation)
    609             returnstring = build_json_output(docmeta)
    610         else:  # txt
--> 611             returnstring = xmltotxt(docmeta['body'], include_formatting, include_links)
    612             if docmeta['commentsbody'] is not None:
    613                 returnstring += '\n' + xmltotxt(docmeta['commentsbody'], include_formatting, include_links)

/usr/local/lib/python3.8/site-packages/trafilatura/xml.py in xmltotxt(xmloutput, include_formatting, include_links)
    219     # remove and insert into the previous tag
    220     for element in xmloutput.xpath('//hi|//ref'):
--> 221         merge_with_parent(element, include_formatting, include_links)
    222         continue
    223     # iterate and convert to list of strings

/usr/local/lib/python3.8/site-packages/trafilatura/xml.py in merge_with_parent(element, include_formatting, include_links)
    196     if parent is None:
    197         return
--> 198     full_text = replace_element_text(element, include_formatting, include_links)
    199     previous = element.getprevious()
    200     if previous is not None:

/usr/local/lib/python3.8/site-packages/trafilatura/xml.py in replace_element_text(element, include_formatting, include_links)
    180     # handle links
    181     if include_links is True and element.tag == 'ref':
--> 182         element.text = ''.join(['[', element.text, ']', '(', element.get('target'), ')'])
    183     # handle text
    184     if element.text is not None and element.tail is not None:

TypeError: sequence item 1: expected str instance, NoneType found
```

**Comment by adbar** [comment] 2021-03-18 17:25
If you install the latest version from the repository you should no
longer see such errors:

pip3 install -U git+https://github.com/adbar/trafilatura.git

However the underlying problem isn't completely solved, they are still
links without text or target.

**Comment by adbar** [comment] 2021-10-08 12:29
@tadeoos I'm closing the issue now that it appears to be fixed (I cannot reproduce it using the latest version). Please free feel to re-open it if you spot a problem.

**Closed by adbar** 2021-10-08 12:29 UTC
Labels: bug
