### ISSUE TITLE
Exception thrown: Unhashable type: 'slice'

### ISSUE THREAD

**Issue by dmoklaf** [adbar/trafilatura#111] opened 2021-08-21 11:24 UTC
The following stack trace has been thrown (see below) while parsing a web page.

Software versions:
MacOS 11.5.2
Python 3.9.5
Lxml 4.6.3
Trafilatura 0.9.1

A git blame reveals this line of code is new and has been introduced by the git commit 66ef5370f7feed894b92109dcac1626b0cbf2462
pushed 25 days ago with the message "`PR: merge attempt`"

It seems the `parent['@context']` object is a dictionary and not a sequence (list or tuple), trigering this bug as the slicing operation `[:-10:]` expects a sequence.

As a confirmation, switching to a previous Trafilatura version (0.9.0) makes the bug disappear. So this bug was indeed introduced by this git commit.

Stack trace:
```
... (non-trafilatura code, i.e., my client code, calling directly trafilatura.core.bare_extraction with a pre-parsed LXML tree) ...
File "/usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.9/site-packages/trafilatura/core.py", line 748, in bare_extraction
    docmeta = extract_metadata(tree, url, date_extraction_params, no_fallback)
  File "/usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.9/site-packages/trafilatura/metadata.py", line 327, in extract_metadata
    metadata = extract_meta_json(tree, metadata)
  File "/usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.9/site-packages/trafilatura/metadata.py", line 49, in extract_meta_json
    metadata = extract_json(schema, metadata)
  File "/usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.9/site-packages/trafilatura/json_metadata.py", line 28, in extract_json
    if '@context' not in parent or parent['@context'][-10:].lower() != 'schema.org':
TypeError: unhashable type: 'slice'
```

**Comment by adbar** [comment] 2021-08-24 13:37
Hi @dmoklaf, thanks for the bug report. There is indeed a problem with the release 0.9.1.
I addressed it in https://github.com/adbar/trafilatura/commit/8e524da64113c529256c1d6abe5b77253111fbfd and @felipehertzer in 718bc25bce20a716a92e7b43c3def50951e7b7e2.

@felipehertzer Could you please check if we both fixed it the same way?

**Comment by felipehertzer** [comment] 2021-08-25 00:32
Hi @dmoklaf, could you provide the example URL?

**Comment by dmoklaf** [comment] 2021-08-25 07:04
I did not save it unfortunately but I can test my program using a git version of your choice and try to find another one (my program processes news incrementally from many sources so there is a good probability I can find another one).

**Comment by felipehertzer** [comment] 2021-08-25 07:11
Hey, alright, I think that the error @context was not a string, but I didn't find any site that uses array in this field, I just sent a commit that checks these fields. Could you test it? #110, please let me know. Thanks.

**Comment by dmoklaf** [comment] 2021-08-25 07:36
> Hi @dmoklaf, thanks for the bug report. There is indeed a problem with the release 0.9.1.
> I addressed it in [8e524da](https://github.com/adbar/trafilatura/commit/8e524da64113c529256c1d6abe5b77253111fbfd) and @felipehertzer in [718bc25](https://github.com/adbar/trafilatura/commit/718bc25bce20a716a92e7b43c3def50951e7b7e2).
> 
> @felipehertzer Could you please check if we both fixed it the same way?

I don't think these patches address this bug as they don't modify the beginning of the extract_json function but downstream code within this function. My error was triggered at the very beginning of this function, on line 28, see stack trace. In some cases the "parent" variable contains a list and not a dict, triggering this bug.

Today's run triggered no error with the base faulty version (0.9.1) so I could not reproduce the bug yet. I will try every day until I recover a URL to reproduce the issue (I am sorry I shall have kept it but it slipped through...)

**Comment by adbar** [comment] 2021-09-14 11:39
@dmoklaf Thanks for the feedback, please keep us informed in case you spot a reproducible bug.

**Comment by dmoklaf** [comment] 2021-09-14 11:50
Yes will do

**Comment by adbar** [comment] 2021-11-16 18:17
I'm closing this for now because potential bugs should be caught by the `try-exception` loop referenced above.

**Closed by adbar** 2021-11-16 18:17 UTC
Labels: bug
