### ISSUE TITLE
Parsing Protocol Articles Fails To Extract Article Content

### ISSUE THREAD

**Issue by hpowers** [adbar/trafilatura#112] opened 2021-08-28 11:18 UTC
First, let me say awesome work, awesome project!  I've replaced newspaper3k with trafilatura and am not looking back.

Here's a maybe interesting use case where it fails
https://www.protocol.com/project-aria-gemini-ar-glasses

The text it pulls is something about signing up for a newsletter.
newspaper3, jusText, readability all do the same.

Safari's reader mode and getpocket correctly extract the article.

Maybe getpocket is implementing some custom logic for protocol, but I doubt safari is.

Any thoughts?

**Comment by felipehertzer** [comment] 2021-09-01 23:07
Hello, sorry for the delay, Protocol.com uses a tag that is not common to define the content of the page, I just add this tag in my pull request #110 . The solution will be in master soon.

**Comment by adbar** [comment] 2021-09-14 12:24
@hpowers Thanks, I appreciate your feedback! The extraction works on my machine, I cannot reproduce the bug. Could you please try the latest version of `trafilatura` and tell me if you still run into the issue?

@felipehertzer you chose `contains(@class, "body-description")` where `contains(@class, "article__body")` is better because it's potentially more generic. Besides, it's already in the code ;)

**Comment by adbar** [comment] 2021-10-08 12:25
Closing the issue now that it appears to be fixed.

**Closed by adbar** 2021-10-08 12:25 UTC
Labels: question
